name: kinematics3d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - imutils
  - toml
  - pandas
  - numpy
  - tensorflow=2.10 # deeplabcut only supports up to tensorflow 2.10, but if it gets pulled in automatically through pip the GPU support didn't work
  - scipy=1.10 # otherwise we get this error https://github.com/lambdaloop/anipose/issues/127
  - pip:
    - anipose==1.0.1 # this needs to be 1.1.0 or we get this error https://github.com/lambdaloop/anipose/issues/111 (or downgrade pandas)
    - aniposelib==0.4.3
    - opencv-contrib-python==4.5.5.64
    - mycolorpy
    - deeplabcut[tf]