#!/usr/bin/env python
""" Script to run anipose.
    Example use:
    >>> run_anipose --txt_dir dirs.txt --filter_2d --calibrate --triangulate --remove3d

    Note that if such txt does not exist you first need to launch run_deeplabcut to create the file.
    Check run_deeplabcut for details.
"""

import argparse
from kinematics3d.anipose_pipeline import run_pipeline_from_txt


def parse_args():
    """ Argument parser. """
    parser = argparse.ArgumentParser(
        description='Pipeline to automatize Anipose run',
        formatter_class=(
            lambda prog:
            argparse.HelpFormatter(prog, max_help_position=50)
        ),
    )
    parser.add_argument(
        '-txt',
        '--txt_dir',
        type=str,
        default=None,
        help='Input text directory',
    )
    parser.add_argument(
        '--filter_2d',
        default=False,
        action='store_true',
        help='Filter 2D poses',
    )
    parser.add_argument(
        '--calibrate',
        default=False,
        action='store_true',
        help='Calibrate using the animal data',
    )
    parser.add_argument(
        '--triangulate',
        default=False,
        action='store_true',
        help='Triangulate 2D poses',
    )
    parser.add_argument(
        '--remove3d',
        default=False,
        action='store_true',
        help='Remove existing 3D poses',
    )
    return parser.parse_args()


if __name__ == '__main__':

    args = parse_args()

    run_pipeline_from_txt(
        txt_dir=args.txt_dir,
        filter_2d=args.filter_2d,
        calibrate=args.calibrate,
        triangulate=args.triangulate,
        remove_pose3d=args.remove3d
    )
